#
# Copyright BYOWares
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format


[versions]
snake = "2.3"


[libraries]
mp3-jlayer = { group = "com.github.umjammer", name = "jlayer", version = "1.0.3" }
mp3-spi = { group = "com.github.umjammer", name = "mp3spi", version = "1.9.17" }
mp3-titr = { group = "com.github.umjammer.tritonus", name = "tritonus-remaining", version = "0.3.13" }
mp3-tits = { group = "com.github.umjammer.tritonus", name = "tritonus-share", version = "0.3.13" }
mp3-uni-char = { group = "com.github.albfernandez", name = "juniversalchardet", version = "2.5.0" }
mp3-vavi-commons = { group = "com.github.umjammer.vavi-commons", name = "vavi-commons", version = "1.1.13" }
mp3-vavi-sound = { group = "com.github.umjammer", name = "vavi-sound", version = "1.0.19" }

snakeYaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snake" }


[bundles]
mp3 = ["mp3-spi", "mp3-jlayer", "mp3-tits", "mp3-titr", "mp3-vavi-sound", "mp3-vavi-commons", "mp3-uni-char"]

yamlImpl = ["snakeYaml"]
